name: autofix.ci

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
        with:
          enable-cache: "auto"

      - name: Sync dependencies
        run: uv sync

      - name: Format code
        run: |
          set +e
          uv run ruff format .
          set -e

      - name: Lint code (fix)
        run: |
          set +e
          uv run ruff check --fix .
          set -e

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # v1.3.3
